model_params:
    N_INPUT: 2
    N_OUTPUT: 1
    N_HIDDEN: 32
    N_LAYERS: 3

training_params:
    random_seeds: 10
    learning_rate: 0.01  # increased from 0.001
    training_epochs: 15001

inversion_params:
    lambda_bc: 100.0  # increased from 10.0
    lambda_pde: 1.0  # increased from 1.0
    lambda_ic: 1.0  # reduced down from 10.0
    inversion_epochs: 10001  # increased from 5000
    inv_learning_rate: 0.0001  # decreased from 0.1