model_params:
    N_INPUT: 2
    N_OUTPUT: 1
    N_HIDDEN: 32
    N_LAYERS: 3

training_params:
    random_seeds: 10
    learning_rate: 0.001
    training_epochs: 5001

hyperparameters:
    alpha_true: 0.1  # True value of thermal diffusivity
    lambda_bc: 100.0  # Weight for boundary loss
    lambda_pde: 1.0  # Weight for PDE loss
    lambda_ic: 100.0  # Weight for initial condition loss
    lambda_data: 10.0  # Weight for data loss (during inversion)

equation:
    type: "heat_eq_1D"
    # type: "heat_eq_1D_with_source"